name: Convert LaTeX to Markdown

on:
  push:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Convert LaTeX to Markdown
        run: pandoc main.tex -o cv.md

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v8
        with:
          add: cv.md
          message: "Automatic conversion: LaTeX to Markdown"
          github-token: ${{ secrets.GITHUB_TOKEN }}
