name: Convert LaTeX to PDF

on:
  push:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get install texlive-full

      - name: Convert LaTeX to PDF
        uses: pdfkit/pdfkit:v1.2.0
        with:
          path: ./main.tex  # Path to your LaTeX file
          engine: pdflatex  # Specify pdflatex engine

      - name: Upload Artifact (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: pdf-artifact
          path: CV.pdf
