name: Convert LaTeX to PDF and Images

on:
  push:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get install texlive-full imagemagick

      - name: Convert LaTeX to PDF
        uses: pdfkit/pdfkit:v1.2.0
        with:
          path: ./main.tex  # Path to your LaTeX file
          engine: pdflatex  # Specify pdflatex engine

      - name: Split PDF to Images
        run: |
          pageCount=$(pdfinfo main.pdf | grep Pages | awk '{print $2}')
          for ((i=1; i<=$pageCount; i++)); do
            convert main.pdf -quality 100 -density 300 "page-$i.jpg"[$i]
          done

      - name: Upload Artifacts (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: CV.pdf,*.jpg  # Upload both PDF and images
